### PR TITLE
docker images for mirage / rump

### PR DESCRIPTION
**Pull request by mor1**

### CODE REVIEW

**Comment by mato** [comment]
Sounds good, I'd leave all bits to actually run anything out entirely for now. You can of course keep them around in your own Dockerfile(s).

**Comment by mor1** [comment]
Don't merge yet, just testing it out

**Comment by mor1** [comment]
Ok, I think this one works now -- should be ready to merge.
Generated image is a chunk smaller too (~800MB vs 1.3GB). 
Built image uploaded to  https://hub.docker.com/r/mor1/rumprun-mirage-toolchain-x86_64/

**Comment by mato** [comment]
This looks good to me. Merging as-is for now, we can improve the image size further later. I'll try and hook this up to the Docker Hub automated builds tomorrow.

**Pull request merged**
